# Generated by Django 4.0.1 on 2022-02-08 17:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_ability_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна проживания'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Район проживания'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='4b5fcf6850e0491a8e8bcb1281bb9213', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='abilities',
            field=models.ManyToManyField(blank=True, max_length=10, to='account.Ability'),
        ),
    ]
