# Generated by Django 4.0.1 on 2022-02-08 17:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_country_user_district_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='61c30debe1494df9b9ae639cb21cc588', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
