# Generated by Django 4.0.1 on 2022-02-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_registrationlinkgenerator_url_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='10d0b0b5ebc045758e1d8f4676206f5c', editable=False, max_length=64),
        ),
    ]
