# Generated by Django 4.0.1 on 2022-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_registrationlinkgenerator_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='4e281ccfa3fc44e590fe84a0ccdc8e28', editable=False, max_length=64),
        ),
    ]
