# Generated by Django 4.0.1 on 2022-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_registrationlinkgenerator_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='b1cdd54a11f841c1b5e4cf1a7638b85c', editable=False, max_length=64),
        ),
    ]
