# Generated by Django 4.0.1 on 2022-02-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_country_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='c384af45f45a4b3e80728813733127f9', editable=False, max_length=64),
        ),
    ]
