# Generated by Django 4.0.1 on 2022-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_registrationlinkgenerator_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='a584911564534d368f076c73a5d3c159', editable=False, max_length=64),
        ),
    ]
