# Generated by Django 4.0.1 on 2022-02-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('account', '0013_alter_registrationlinkgenerator_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationlinkgenerator',
            name='community_invited',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Пригласившое сообщество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationlinkgenerator',
            name='url_hash',
            field=models.CharField(default='6c5e4783ae034887a6397561e20af5af', editable=False, max_length=64),
        ),
    ]
