# Generated by Django 4.0.1 on 2022-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_registrationlinkgenerator_url_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationLinkGenerator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='1232131', max_length=20, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
