# Generated by Django 4.0.1 on 2022-08-08 12:17

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_delete_registrationlinkgenerator_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
