# Generated by Django 4.0.1 on 2022-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.CharField(default='123213', max_length=20, unique=True, verbose_name='id телеграм'),
            preserve_default=False,
        ),
    ]
