# Generated by Django 4.0.1 on 2022-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.TextField(default='Пользователь не заблокирован', max_length=1000, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
    ]
