# Generated by Django 4.0.1 on 2022-08-10 17:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='✋')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.goodcategory')),
            ],
            options={
                'verbose_name': 'Категория товаров/услуг',
                'verbose_name_plural': 'Категории товаров/услуг',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('type', models.CharField(choices=[('good', 'Товар'), ('service', 'Услуга')], max_length=20, verbose_name='Тип')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'На модерации'), (2, 'Запрещено модератором'), (3, 'Опубликовано')], default=0, verbose_name='Состояние')),
                ('moderation_disallow_reason', models.TextField(verbose_name='Причина отказа модератором')),
                ('description', models.TextField(verbose_name='Описание')),
                ('condition', models.PositiveSmallIntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Состояние товара')),
                ('price_currency', models.DecimalField(decimal_places=2, default=Decimal('-1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-1'))], verbose_name='Стоимость в реальной валюте')),
                ('price_gifts', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Стоимость в дарах')),
                ('ready_to_change', models.BooleanField(default=False, verbose_name='Готов обменять')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('images', models.JSONField(verbose_name='Фотографии')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.goodcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар/услуга',
                'verbose_name_plural': 'Товары/услуги',
            },
        ),
    ]
