# Generated by Django 4.0.1 on 2022-08-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcategory',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='goodcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.goodcategory'),
        ),
    ]
