# Generated by Django 4.0.1 on 2022-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_good_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='images',
            field=models.JSONField(blank=True, null=True, verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='good',
            name='moderation_disallow_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа модератором'),
        ),
    ]
