# Generated by Django 4.0.1 on 2022-08-15 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_good_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='images',
            field=models.JSONField(blank=True, null=True, verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='good',
            name='moderation_disallow_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа модератором'),
        ),
    ]
