# Generated by Django 4.0.1 on 2022-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_good_created_at_good_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'На модерации'), (2, 'Запрещено модератором'), (3, 'Опубликовано'), (4, 'Удалено'), (5, 'Продано')], default=0, verbose_name='Состояние'),
        ),
    ]
