# Generated by Django 4.0.1 on 2022-08-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_good_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='type',
        ),
    ]
