# Generated by Django 4.0.1 on 2022-08-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_good_created_at_good_updated_at_and_more'),
        ('trade', '0006_alter_good_state'),
    ]

    operations = [
    ]
