# Generated by Django 4.0.1 on 2022-08-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.good'),
        ),
    ]
