# Generated by Django 4.0.1 on 2022-08-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_alter_uploadedimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='images',
        ),
    ]
